# My Starship Prompt Config

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# The Prompt
format = """
[](#252526)\
$os\
$username\
[](bg:#2D2D30 fg:#252526)\
[  ](bg:#2D2D30)\
$directory\
[](bg:#3E3E42 fg:#2D2D30)\
$git_branch\
$git_status\
[](bg:#007ACC fg:#3E3E42)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$nix_shell\
$package\
$perl\
$php\
$python\
$ruby\
$rust\
$scala\
[](bg:#0451A5 fg:#007ACC)\
$docker_context\
[](bg:#252526 fg:#0451A5)\
[ ](bg:#252526)\
$time\
[ ](fg:#252526)\
"""
right_format = """$cmd_duration"""
continuation_prompt = "[ ]($style)"
command_timeout = 5000
follow_symlinks = true

# Disable the blank line at the start of the prompt
add_newline = true

### Left Side
[username]
show_always = true
style_user = "bg:#252526"
style_root = "bg:#252526"
format = "[$user ]($style)"

[directory]
style = "bg:#2D2D30"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[os]
disabled = false
style = "bg:#252526"

[os.symbols]
SUSE = " "
Raspbian = "󰐿 "
Linux = "󰌽 "
Gentoo = "󰣨 "
Arch = "󰣇 "
Debian = "󰣚 "
Windows = " "
Macos = " "

[c]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = " "
style = "bg:#0451A5"
format = "[ $symbol $context ]($style) $path"

[elixir]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[elm]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[git_branch]
symbol = " "
style = "bg:#3E3E42"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#3E3E42"
format = "[$all_status$ahead_behind ]($style)"

[golang]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[haskell]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[julia]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[lua]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[nodejs]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[nim]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[nix_shell]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[package]
symbol = "󰏗 "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[perl]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[php]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[python]
symbol = " "
pyenv_version_name = false
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = ""
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[scala]
symbol = " "
style = "bg:#007ACC"
format = "[ $symbol ($version) ]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#252526"
format = "[ $time ]($style)"

### Right Prompt
[cmd_duration]
min_time = 5000
show_milliseconds = true
format = "took [$duration]($style)"
style = "#B5A700"
