#!/bin/env bash
# My powermenu made with rofi

# What is shown to the user
chosen=$(printf "  Shudown\n  Restart\n󰍃  Log Out\n  Lock" | rofi -dmenu -i -theme "nord" -theme-str "window {width: 8em;} listview {lines: 6;}")

# Do what is chosen
case "$chosen" in
	"  Shudown") systemctl poweroff ;;
	"  Restart") systemctl reboot ;;
	"󰍃  Log Out") loginctl terminate-session $XDG_SESSION_ID ;;
	"  Lock") i3lock-fancy -g ;;
	*) exit 1 ;;
esac
