#!/bin/env bash

player="$1"
cutpoint="$2"

# Get the playback status
status=$(playerctl status --player="$player")

# Check if the status is "Playing"
if [ "$status" = "Playing" ]; then
    # Get the title and cut off after 15 letters
    title=$(playerctl metadata title --player="$player" | cut -c 1-"$cutpoint")
    echo "$title"
else
    # Set the title to "Not Playing/Paused"
    echo "Not Playing/Paused"
fi
