#!/bin/env bash

togglepause() {
    playerctl -p "$(pgrep -f "YouTube - Brave")" play-pause
}

next() {
    playerctl -p "$(pgrep -f "YouTube - Brave")" next
}

previous() {
    playerctl -p "$(pgrep -f "YouTube - Brave")" previous
}

forward() {
    playerctl -p "$(pgrep -f "YouTube - Brave")" position 5+
}

backward() {
    playerctl -p "$(pgrep -f " YouTube - Brave")" position 5-
}

# Check the first argument to decide what to do
case "$1" in
    --togglepause)
        togglepause ;;
    --skip)
        next ;;
    --backskip)
        previous ;;
    --forward)
        forward ;;
    --backward)
        backward ;;
    *)
        echo "Unknown arg: $1" ;;
esac
