#!/bin/env bash

num="$2"
volume_inc(){
  pamixer -i "$num"
}

volume_dec(){
  pamixer -d "$num"
}

volume_togglemute(){
  pamixer --toggle-mute
}

volume_stream(){
  # Main Tracks
  pactl load-module module-null-sink sink_name="main_track" sink_properties=device.description="Main_Track"
  pactl load-module module-loopback latency_msec=1 source=main_track.monitor sink=alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink

  # Music Tracks
  pactl load-module module-null-sink sink_name="music_track" sink_properties=device.description="Music_Track"
  pactl load-module module-loopback latency_msec=1 source=music_track.monitor sink=alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink
  xcowsay "Streaming Audio On"
}

case "$1" in
  --togglemute)
    volume_togglemute ;;
  --inc)
    volume_inc ;;
  --dec)
    volume_dec  ;;
  --stream)
    volume_stream  ;;
  *)
    echo "Unkown Arg" ;;
esac
